// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1tUPT5cRNBsN1Eyc0ZbZaNXvvWvyURxw',
    appId: '1:427789228693:web:e32dfecc5aacc1d719d99c',
    messagingSenderId: '427789228693',
    projectId: 'leafy-c803d',
    authDomain: 'leafy-c803d.firebaseapp.com',
    storageBucket: 'leafy-c803d.appspot.com',
    measurementId: 'G-C0BTXPZ8HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYl0l3dBJ4lEhtUuprjpdMXBLsMo_yJ9c',
    appId: '1:427789228693:android:8a26b10823423c2719d99c',
    messagingSenderId: '427789228693',
    projectId: 'leafy-c803d',
    storageBucket: 'leafy-c803d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALxKrjrQHU1k4bXSZf7eerOGYygnvEexc',
    appId: '1:427789228693:ios:b7f1f8cb6c7fadae19d99c',
    messagingSenderId: '427789228693',
    projectId: 'leafy-c803d',
    storageBucket: 'leafy-c803d.appspot.com',
    iosClientId: '427789228693-02lu5cspnhk156tupbvicd70nc7rafic.apps.googleusercontent.com',
    iosBundleId: 'com.leafy.leafy',
  );
}
